// ignore: constant_identifier_names
const OPENAI_KEY =
    "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";
